default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: app_dev
  username: app
  password: app

test:
  <<: *default
  database: app_test
  username: app
  password: app

production:
  <<: *default
  pool: <%= ENV['DB_POOL'].presence || 5 %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
