apiVersion: v1
kind: Service
metadata:
  name: {{ include "alert-app.fullname" . }}
  labels:
    {{- include "alert-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "alert-app.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.typelb }}
  ports:
    - port: {{ .Values.service.portlb }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "alert-app.selectorLabels" . | nindent 4 }}
